export const site = {
  name: "Oxbow Creatives",
  shortName: "Oxbow",
  tagline: "Branding, websites, Shopify stores, and performance marketing — built as one system, under one roof.",
  phone: "+91 95713 66877",
  phoneRaw: "+919571366877",
  email: "support@oxbowcreatives.com",
  address: "Basement & 1st Floor, Landmark Shopping Centre, Shop No. 5 & 6, Near Durgapura Railway Station, Durgapura, Jaipur, Rajasthan 302018",
  addressShort: "Durgapura, Jaipur, Rajasthan",
  city: "Jaipur, India",
  founded: "2022",
  socials: {
    instagram: "https://www.instagram.com/oxbowcreatives/",
    linkedin: "https://in.linkedin.com/company/oxbow-creatives",
    facebook: "https://www.facebook.com/people/Oxbow-Creatives/61568631520017/",
  },
  clients: [
    "Akera Health", "Azurina x Gouniq", "Balance Breens", "Bird House", "Brokwise",
    "Early Sunday", "Humraha", "Inspire.Ai", "Ishhaara", "Janki",
    "Kameezy", "KM Label", "LMC", "Mohana Poshak",
    "Mulltiply.ai", "Navya Fashion", "Noa Rooftop", "Phutari",
    "Riann Dimonds", "Roslyn By Demi", "Savanna",
    "Siddhi Ananta", "Simply Soho", "Tahiliya", "Tangerine",
    "The Yellow Bow", "Wibrion",
    "Bug Buddy", "The BridgeBoxe", "The Bling Project", "Mirari",
    "Salona Bichona", "Tangelos", "We Are Nativ", "Naree Clothing",
  ],
  reviews: [
    { quote: "Oxbow rebuilt our Shopify store from the ground up. The site finally feels like the brand we set out to build, and it's been smoother to run on the back end too.", name: "Founder", role: "Bug Buddy" },
    { quote: "We came in with a vague idea of what we wanted and left with a full identity — logo, packaging direction and a site that actually represents the brand.", name: "Founder", role: "The BridgeBoxe" },
    { quote: "Their team is easy to work with and quick to respond. The new product photography alone made a noticeable difference to how the brand looks online.", name: "Founder", role: "The Bling Project" },
    { quote: "Oxbow took over our Meta Ads and were upfront about what was working and what wasn't — no inflated promises, just steady, honest reporting.", name: "Founder", role: "Mirari" },
    { quote: "From design to development, everything was handled in-house. That made the whole process far less stressful than working with multiple vendors.", name: "Founder", role: "Salona Bichona" },
    { quote: "Good communication, fair pricing, and a team that actually understands D2C and Shopify — that combination is harder to find than it should be.", name: "Founder", role: "We Are Nativ" },
  ],
};
